name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v3
        env:
          STRIFE_CERTIFICATE: ${{ secrets.STRIFE_CERTIFICATE }}
          STRIFE_CERTIFICATE_PASSWORD: ${{ secrets.STRIFE_CERTIFICATE_PASSWORD }}
          STRIFE_DATABASE_URLS: ${{ secrets.STRIFE_DATABASE_URLS }}
          STRIFE_DATABASE: ${{ secrets.STRIFE_DATABASE }}
        # ... rest of the build job

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        env:
          STRIFE_CERTIFICATE: ${{ secrets.STRIFE_CERTIFICATE }}
          STRIFE_CERTIFICATE_PASSWORD: ${{ secrets.STRIFE_CERTIFICATE_PASSWORD }}
          STRIFE_DATABASE_URLS: ${{ secrets.STRIFE_DATABASE_URLS }}
          STRIFE_DATABASE: ${{ secrets.STRIFE_DATABASE }}